### ISSUE TITLE
[建议] 使用FORCE_LOOK标签时 可选择关闭失明效果

### ISSUE THREAD

**Issue by luoxiawuchen** [TabooLib/chemdah#38]
在某些情况下（深色或暗色调皮肤形象的NPC）应用失明效果可能视觉效果不佳
![image](https://user-images.githubusercontent.com/64759847/175572139-0b1547ae-692e-413a-a72d-f8a9a9b26680.png)
在使用FORCE_LOOK标签时 可选择是否关闭失明效果 保留减速效果

**Comment by Bkm016** [comment]
`0.2.36`

NO_EFFECT:BLINDNESS
