### ISSUE TITLE
[功能建议] 添加手持物品表达式查询命令 如：/chemdah api iteminfo

### ISSUE THREAD

**Issue by luoxiawuchen** [TabooLib/chemdah#51]
在RPG创作环境中，编写收集物品或其他任务，常常需检测带NBT数值的物品，表达式可能会变得非常复杂（如果需要精确匹配）

能否添加一个手持物品查询命令呢？例如/chemdah api iteminfo，可以查询并复制手中的物品表达式

chemdah有类似命令：/chemdah api blockinfo，不过只能查询准星所指方块的信息

![image](https://user-images.githubusercontent.com/64759847/208357443-5dc35127-8002-4e16-9f71-1441eac5f6b5.png)

![image](https://user-images.githubusercontent.com/64759847/208357691-3d972ccd-fe7d-403e-94fd-24068583200c.png)

**Comment by Bkm016** [comment]
Fenestra牛逼
